var http = require("http");
const parseHTML = require("./parseHTML");
//create a server object:
http
  .createServer(function(req, res) {
    const jsonDoc = parseHTML(`
      “Silver linings rain or shine \nThat little red squiggle \nOnly catches me sometimes”\n\nComedy of Erros was a group exhibition curated by Fiona Alison Duncan as an expression of Pillow Talk. Installed at Christopher Schwartz’s STARS gallery (formerly The Gallery At) in Hollywood, California, Comedy of Erros explored errors and eros, spanning a range of entanglements, from economic to sensuous to linguistic. Originally intended to open on April Fools Day 2020, the show was postponed due to the Covid-19 pandemic. Much of the work in the show, programmed the year prior, synchronized with the 2020 zeitgeist; work about virality, sickness, filth, isolation, interdependence, phallic power (the election) and antiracist, intersectional feminist and sex worker activism. As it happens with Duncan, her chosen theme manifest itself in the creative process; comedic, cathartic, sticky “human folly” conflicts and confusions came up. Most of that is unrelatable, secrets, for now. To give one impersonal example, Comedy of Erros was put back on the calendar during a chill phase of the pandemic, only to open right as viral cases amped waaaaay up in LA. We had our visitors. Many missed out. “Next time I’ll call my show Ease of Grace!” Duncan didn’t joke. Haha. It’s life, wherein errors resolved deepen relationships and better work. \n\nIn the end, Comedy of Erros featured artists from five nations of North America: Canada, Mexico, the U.S., the Mi’kmaq First Nations, and the Tohono O’odham Nation. Pippa Garner was the poster girl. Photographed naked by Clifford Prince King, she exhibited one of God’s discarded human prototypes as a sculpture. SoiL Thornton presented a body-safe sex toy cast from dirt, mountable, vibrating, it was made thanks to local pleasure product manufacturer Doc Johnson. Painter Sojourner Truth Parsons exhibited balloons and writing, a rarity. Duncan asked for it. Helium leaks over time, Parsons work went from buoyancy to deflation, like written language’s life cycle (the balloons are red-inflatable). We also had Vaquera, Val Breeder, Takako Yamaguchi, Reynaldo Rivera, Neke Carson, Matt Kenny, John Greyson, Ishi Glinsky, and Fernando Mendez Corona. With archival materials on Ilona Staller and Florynce ‘Flo’ Kennedy, care of The Los Angeles Public Library and the Schlesinger Library at the Radcliffe Institute, Harvard University.
      `);
    res.write(JSON.stringify(jsonDoc, null, 2)); //write a response to the client
    res.end(); //end the response
  })
  .listen(8080); //the server object listens on port 8080
